package sv.ues.fia.eisi.proyecto01_antojitos.db;

import android.database.sqlite.SQLiteDatabase;
import android.util.Log;

public class BaseDatosSeeder {

    public static void insertarDatosIniciales(SQLiteDatabase db) {
        Log.i("BaseDatosSeeder", "Insertando datos iniciales...");
        // 1 - Deshabilitar temporalmente FK y limpiar tablas en orden inverso
        db.execSQL("PRAGMA foreign_keys=OFF;");

        db.execSQL("DELETE FROM ACCESOUSUARIO;");
        db.execSQL("DELETE FROM OPCIONCRUD;");
        db.execSQL("DELETE FROM USUARIO;");

        db.execSQL("DELETE FROM DETALLEPEDIDO;");
        db.execSQL("DELETE FROM REPARTOPEDIDO;");
        db.execSQL("DELETE FROM DIRECCION;");
        db.execSQL("DELETE FROM DATOSPRODUCTO;");
        db.execSQL("DELETE FROM CREDITO;");
        db.execSQL("DELETE FROM FACTURA;");
        db.execSQL("DELETE FROM PEDIDO;");
        db.execSQL("DELETE FROM TIPOEVENTO;");
        db.execSQL("DELETE FROM REPARTIDOR;");
        db.execSQL("DELETE FROM CLIENTE;");
        db.execSQL("DELETE FROM SUCURSAL;");
        db.execSQL("DELETE FROM PRODUCTO;");
        db.execSQL("DELETE FROM CATEGORIAPRODUCTO;");
        db.execSQL("DELETE FROM DISTRITO;");
        db.execSQL("DELETE FROM MUNICIPIO;");
        db.execSQL("DELETE FROM DEPARTAMENTO;");
        // Resetear secuencias AUTOINCREMENT
        db.execSQL("DELETE FROM sqlite_sequence;");
        db.execSQL("PRAGMA foreign_keys=ON;");

        db.execSQL("INSERT OR REPLACE INTO USUARIO(ID_USUARIO, NOM_USUARIO, CLAVE) VALUES " +
                "('SU','superusuario','12345')," +
                "('CL','cliente','123')," +
                "('RP','repartidor','123')," +
                "('SC','sucursal','123');");

        // 2 - Datos para OPCIONCRUD
        db.execSQL("INSERT OR REPLACE INTO OPCIONCRUD(ID_OPCION, DES_OPCION, NUM_CRUD) VALUES " +
                "('cliente_crear',     'Crear Cliente',       1)," +
                "('cliente_consultar', 'Consultar Cliente',   2)," +
                "('cliente_editar',    'Editar Cliente',      3)," +
                "('cliente_eliminar',  'Eliminar Cliente',    4)," +
                "('producto_consultar','Consultar Producto',  2)," +   // solo lectura para clientes
                "('reparto_consultar', 'Consultar Reparto',   2)," +
                "('todo_admin',        'Acceso total',        0);");    // 0 = comodín para superusuario

        // 3 - Datos para ACCESOUSUARIO
        // -- Superusuario: una sola fila comodín
        db  .execSQL("INSERT OR REPLACE INTO ACCESOUSUARIO(ID_OPCION, ID_USUARIO) VALUES " +
                "('todo_admin','SU');");

        // -- Cliente: solo lectura de productos y sus propios datos
        db.execSQL("INSERT OR REPLACE INTO ACCESOUSUARIO(ID_OPCION, ID_USUARIO) VALUES " +
                "('cliente_consultar','CL')," +
                "('producto_consultar','CL');");

        // -- Repartidor: puede consultar repartos
        db.execSQL("INSERT OR REPLACE INTO ACCESOUSUARIO(ID_OPCION, ID_USUARIO) VALUES " +
                "('reparto_consultar','RP');");

        // -- Sucursal: ejemplo de permisos variados
        db.execSQL("INSERT OR REPLACE INTO ACCESOUSUARIO(ID_OPCION, ID_USUARIO) VALUES " +
                "('producto_consultar','SC')," +
                "('cliente_consultar','SC');");


        // 2 - Datos para DEPARTAMENTO
        db.execSQL("INSERT OR REPLACE INTO DEPARTAMENTO(ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO, ACTIVO_DEPARTAMENTO) VALUES (1,'San Salvador', 1);");
        db.execSQL("INSERT OR REPLACE INTO DEPARTAMENTO(ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO, ACTIVO_DEPARTAMENTO) VALUES (2,'La Libertad', 1);");
        db.execSQL("INSERT OR REPLACE INTO DEPARTAMENTO(ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO, ACTIVO_DEPARTAMENTO) VALUES (3,'Santa Ana', 1);");
        db.execSQL("INSERT OR REPLACE INTO DEPARTAMENTO(ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO, ACTIVO_DEPARTAMENTO) VALUES (4,'San Miguel', 1);");
        db.execSQL("INSERT OR REPLACE INTO DEPARTAMENTO(ID_DEPARTAMENTO,NOMBRE_DEPARTAMENTO, ACTIVO_DEPARTAMENTO) VALUES (5,'Usulután', 1);");

        // 3 - Datos para MUNICIPIO
        db.execSQL("INSERT OR REPLACE INTO MUNICIPIO(ID_MUNICIPIO, ID_DEPARTAMENTO, NOMBRE_MUNICIPIO, ACTIVO_MUNICIPIO) VALUES (1,1,'San Salvador', 1);");
        db.execSQL("INSERT OR REPLACE INTO MUNICIPIO(ID_MUNICIPIO, ID_DEPARTAMENTO, NOMBRE_MUNICIPIO, ACTIVO_MUNICIPIO) VALUES (2,2,'Santa Tecla', 1);");
        db.execSQL("INSERT OR REPLACE INTO MUNICIPIO(ID_MUNICIPIO, ID_DEPARTAMENTO, NOMBRE_MUNICIPIO, ACTIVO_MUNICIPIO) VALUES (3,3,'Metapán', 1);");
        db.execSQL("INSERT OR REPLACE INTO MUNICIPIO(ID_MUNICIPIO, ID_DEPARTAMENTO, NOMBRE_MUNICIPIO, ACTIVO_MUNICIPIO) VALUES (4,4,'San Miguel', 1);");
        db.execSQL("INSERT OR REPLACE INTO MUNICIPIO(ID_MUNICIPIO, ID_DEPARTAMENTO, NOMBRE_MUNICIPIO, ACTIVO_MUNICIPIO) VALUES (5,5,'Usulután', 1);");

        // 4 - Datos para DISTRITO
        db.execSQL("INSERT OR REPLACE INTO DISTRITO(ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_DISTRITO,CODIGO_POSTAL) VALUES (1,1,1,'Centro','1101');");
        db.execSQL("INSERT OR REPLACE INTO DISTRITO(ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_DISTRITO,CODIGO_POSTAL) VALUES (2,2,2,'Merliot','1102');");
        db.execSQL("INSERT OR REPLACE INTO DISTRITO(ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_DISTRITO,CODIGO_POSTAL) VALUES (3,3,3,'Metapán Norte','1103');");
        db.execSQL("INSERT OR REPLACE INTO DISTRITO(ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_DISTRITO,CODIGO_POSTAL) VALUES (4,4,4,'Ciudad Pacífica','1104');");
        db.execSQL("INSERT OR REPLACE INTO DISTRITO(ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_DISTRITO,CODIGO_POSTAL) VALUES (5,5,5,'Puerto Parada','1105');");

        // 5 - Datos para CATEGORIAPRODUCTO
        db.execSQL("INSERT OR REPLACE INTO CATEGORIAPRODUCTO(ID_CATEGORIAPRODUCTO,NOMBRE_CATEGORIA,DESCRIPCION_CATEGORIA,DISPONIBLE_CATEGORIA,HORA_DISPONIBLE_DESDE,HORA_DISPONIBLE_HASTA,ACTIVO_CATEGORIAPRODUCTO) "
                + "VALUES (1,'Antojitos','Comida típica',1,'15:00','18:00',1);");
        db.execSQL("INSERT OR REPLACE INTO CATEGORIAPRODUCTO(ID_CATEGORIAPRODUCTO,NOMBRE_CATEGORIA,DESCRIPCION_CATEGORIA,DISPONIBLE_CATEGORIA,HORA_DISPONIBLE_DESDE,HORA_DISPONIBLE_HASTA,ACTIVO_CATEGORIAPRODUCTO) "
                + "VALUES (2,'Bebidas','Bebidas frías',1,'00:00','23:59',1);");
        db.execSQL("INSERT OR REPLACE INTO CATEGORIAPRODUCTO(ID_CATEGORIAPRODUCTO,NOMBRE_CATEGORIA,DESCRIPCION_CATEGORIA,DISPONIBLE_CATEGORIA,HORA_DISPONIBLE_DESDE,HORA_DISPONIBLE_HASTA,ACTIVO_CATEGORIAPRODUCTO) "
                + "VALUES (3,'Comidas rápidas','Hamburguesas y hotdogs',1,'10:00','22:00',1);");
        db.execSQL("INSERT OR REPLACE INTO CATEGORIAPRODUCTO(ID_CATEGORIAPRODUCTO,NOMBRE_CATEGORIA,DESCRIPCION_CATEGORIA,DISPONIBLE_CATEGORIA,HORA_DISPONIBLE_DESDE,HORA_DISPONIBLE_HASTA,ACTIVO_CATEGORIAPRODUCTO) "
                + "VALUES (4,'Postres','Dulces típicos',1,'12:00','20:00',1);");
        db.execSQL("INSERT OR REPLACE INTO CATEGORIAPRODUCTO(ID_CATEGORIAPRODUCTO,NOMBRE_CATEGORIA,DESCRIPCION_CATEGORIA,DISPONIBLE_CATEGORIA,HORA_DISPONIBLE_DESDE,HORA_DISPONIBLE_HASTA,ACTIVO_CATEGORIAPRODUCTO) "
                + "VALUES (5,'Platos fuertes','Almuerzos tradicionales',1,'11:00','15:00',1);");

        // 6 - Datos para PRODUCTO
        db.execSQL("INSERT OR REPLACE INTO PRODUCTO(ID_PRODUCTO,ID_CATEGORIAPRODUCTO,NOMBRE_PRODUCTO,DESCRIPCION_PRODUCTO,ACTIVO_PRODUCTO) "
                + "VALUES (1,1,'Pupusa de Queso','Clásica pupusa salvadoreña',1);");
        db.execSQL("INSERT OR REPLACE INTO PRODUCTO(ID_PRODUCTO,ID_CATEGORIAPRODUCTO,NOMBRE_PRODUCTO,DESCRIPCION_PRODUCTO,ACTIVO_PRODUCTO) "
                + "VALUES (2,1,'Pupusa Revueltas','Con chicharrón, queso y frijoles',1);");
        db.execSQL("INSERT OR REPLACE INTO PRODUCTO(ID_PRODUCTO,ID_CATEGORIAPRODUCTO,NOMBRE_PRODUCTO,DESCRIPCION_PRODUCTO,ACTIVO_PRODUCTO) "
                + "VALUES (3,2,'Horchata','Bebida tradicional salvadoreña',1);");
        db.execSQL("INSERT OR REPLACE INTO PRODUCTO(ID_PRODUCTO,ID_CATEGORIAPRODUCTO,NOMBRE_PRODUCTO,DESCRIPCION_PRODUCTO,ACTIVO_PRODUCTO) "
                + "VALUES (4,3,'Hamburguesa','Con papas y bebida',1);");
        db.execSQL("INSERT OR REPLACE INTO PRODUCTO(ID_PRODUCTO,ID_CATEGORIAPRODUCTO,NOMBRE_PRODUCTO,DESCRIPCION_PRODUCTO,ACTIVO_PRODUCTO) "
                + "VALUES (5,4,'Empanada de Plátano','Rellena de leche',1);");

        // 7 - Datos para SUCURSAL
        db.execSQL("INSERT OR REPLACE INTO SUCURSAL(ID_SUCURSAL,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_SUCURSAL,DIRECCION_SUCURSAL,TELEFONO_SUCURSAL,HORARIO_APERTURA_SUCURSAL,HORARIO_CIERRE_SUCURSAL,ACTIVO_SUCURSAL) "
                + "VALUES (1,1,1,1,'Sucursal Centro','Calle El Progreso','2200-1111','08:00','20:00',1);");
        db.execSQL("INSERT OR REPLACE INTO SUCURSAL(ID_SUCURSAL,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_SUCURSAL,DIRECCION_SUCURSAL,TELEFONO_SUCURSAL,HORARIO_APERTURA_SUCURSAL,HORARIO_CIERRE_SUCURSAL,ACTIVO_SUCURSAL) "
                + "VALUES (2,2,2,2,'Sucursal Merliot','Blvd. Merliot','2200-2222','09:00','21:00',1);");
        db.execSQL("INSERT OR REPLACE INTO SUCURSAL(ID_SUCURSAL,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_SUCURSAL,DIRECCION_SUCURSAL,TELEFONO_SUCURSAL,HORARIO_APERTURA_SUCURSAL,HORARIO_CIERRE_SUCURSAL,ACTIVO_SUCURSAL) "
                + "VALUES (3,3,3,3,'Sucursal Metapán','Av. Central','2200-3333','07:00','19:00',1);");
        db.execSQL("INSERT OR REPLACE INTO SUCURSAL(ID_SUCURSAL,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_SUCURSAL,DIRECCION_SUCURSAL,TELEFONO_SUCURSAL,HORARIO_APERTURA_SUCURSAL,HORARIO_CIERRE_SUCURSAL,ACTIVO_SUCURSAL) "
                + "VALUES (4,4,4,4,'Sucursal San Miguel','Col. Ciudad Pacífica','2200-4444','08:30','19:30',1);");
        db.execSQL("INSERT OR REPLACE INTO SUCURSAL(ID_SUCURSAL,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,NOMBRE_SUCURSAL,DIRECCION_SUCURSAL,TELEFONO_SUCURSAL,HORARIO_APERTURA_SUCURSAL,HORARIO_CIERRE_SUCURSAL,ACTIVO_SUCURSAL) " +
                "VALUES (5,5,5,5,'Sucursal Usulután','Centro Usulután','2200-5555','08:00','18:00',1);");

        // 8 - Datos para CLIENTE
        db.execSQL("INSERT OR REPLACE INTO CLIENTE(ID_CLIENTE,TELEFONO_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,ACTIVO_CLIENTE) "
                + "VALUES (1,'7010-1111','Carlos','Ramírez',1);");
        db.execSQL("INSERT OR REPLACE INTO CLIENTE(ID_CLIENTE,TELEFONO_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,ACTIVO_CLIENTE) "
                + "VALUES (2,'7010-2222','Ana','González',1);");
        db.execSQL("INSERT OR REPLACE INTO CLIENTE(ID_CLIENTE,TELEFONO_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,ACTIVO_CLIENTE) "
                + "VALUES (3,'7010-3333','Luis','Martínez',1);");
        db.execSQL("INSERT OR REPLACE INTO CLIENTE(ID_CLIENTE,TELEFONO_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,ACTIVO_CLIENTE) "
                + "VALUES (4,'7010-4444','Diana','López',1);");
        db.execSQL("INSERT OR REPLACE INTO CLIENTE(ID_CLIENTE,TELEFONO_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,ACTIVO_CLIENTE) "
                + "VALUES (5,'7010-5555','José','Hernández',1);");

        // --- 9 - Datos para REPARTIDOR ---
        db.execSQL("INSERT OR REPLACE INTO REPARTIDOR("
                + "ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,TIPO_VEHICULO,DISPONIBLE,"
                + "TELEFONO_REPARTIDOR,NOMBRE_REPARTIDOR,APELLIDO_REPARTIDOR,ACTIVO_REPARTIDOR) "
                + "VALUES (1,1,1,'Moto',1,'7200-0001','Luis','Gómez',1);");
        db.execSQL("INSERT OR REPLACE INTO REPARTIDOR("
                + "ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,TIPO_VEHICULO,DISPONIBLE,"
                + "TELEFONO_REPARTIDOR,NOMBRE_REPARTIDOR,APELLIDO_REPARTIDOR,ACTIVO_REPARTIDOR) "
                + "VALUES (2,2,2,'Bicicleta',1,'7200-0002','Mario','Ruiz',1);");
        db.execSQL("INSERT OR REPLACE INTO REPARTIDOR("
                + "ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,TIPO_VEHICULO,DISPONIBLE,"
                + "TELEFONO_REPARTIDOR,NOMBRE_REPARTIDOR,APELLIDO_REPARTIDOR,ACTIVO_REPARTIDOR) "
                + "VALUES (3,3,3,'Carro',1,'7200-0003','Tatiana','Martínez',1);");
        db.execSQL("INSERT OR REPLACE INTO REPARTIDOR("
                + "ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,TIPO_VEHICULO,DISPONIBLE,"
                + "TELEFONO_REPARTIDOR,NOMBRE_REPARTIDOR,APELLIDO_REPARTIDOR,ACTIVO_REPARTIDOR) "
                + "VALUES (4,4,4,'Moto',1,'7200-0004','Kevin','Morales',1);");
        db.execSQL("INSERT OR REPLACE INTO REPARTIDOR("
                + "ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,TIPO_VEHICULO,DISPONIBLE,"
                + "TELEFONO_REPARTIDOR,NOMBRE_REPARTIDOR,APELLIDO_REPARTIDOR,ACTIVO_REPARTIDOR) "
                + "VALUES (5,5,5,'Camioneta',1,'7200-0005','Sofía','Aguilar',1);");

        // --- 10 - Datos para TIPOEVENTO ---
        db.execSQL("INSERT OR REPLACE INTO TIPOEVENTO("
                + "ID_TIPO_EVENTO,NOMBRE_TIPO_EVENTO,DESCRIPCION_TIPO_EVENTO,"
                + "MONTO_MINIMO,MONTO_MAXIMO,ACTIVO_TIPOEVENTO) VALUES (1,'Fiesta Infantil','Evento privado',30.00,300.00,1);");
        db.execSQL("INSERT OR REPLACE INTO TIPOEVENTO("
                + "ID_TIPO_EVENTO,NOMBRE_TIPO_EVENTO,DESCRIPCION_TIPO_EVENTO,"
                + "MONTO_MINIMO,MONTO_MAXIMO,ACTIVO_TIPOEVENTO) VALUES (2,'Reunión Empresarial','Coffee break',50.00,400.00,1);");
        db.execSQL("INSERT OR REPLACE INTO TIPOEVENTO("
                + "ID_TIPO_EVENTO,NOMBRE_TIPO_EVENTO,DESCRIPCION_TIPO_EVENTO,"
                + "MONTO_MINIMO,MONTO_MAXIMO,ACTIVO_TIPOEVENTO) VALUES (3,'Cumpleaños','Celebración familiar',25.00,250.00,1);");
        db.execSQL("INSERT OR REPLACE INTO TIPOEVENTO("
                + "ID_TIPO_EVENTO,NOMBRE_TIPO_EVENTO,DESCRIPCION_TIPO_EVENTO,"
                + "MONTO_MINIMO,MONTO_MAXIMO,ACTIVO_TIPOEVENTO) VALUES (4,'Boda Civil','Recepción sencilla',100.00,800.00,1);");
        db.execSQL("INSERT OR REPLACE INTO TIPOEVENTO("
                + "ID_TIPO_EVENTO,NOMBRE_TIPO_EVENTO,DESCRIPCION_TIPO_EVENTO,"
                + "MONTO_MINIMO,MONTO_MAXIMO,ACTIVO_TIPOEVENTO) VALUES (5,'Cena de Fin de Año','Convivio navideño',60.00,600.00,1);");

        // --- 11 - Datos para PEDIDO ---
        db.execSQL("INSERT OR REPLACE INTO PEDIDO("
                + "ID_PEDIDO,ID_CLIENTE,ID_TIPO_EVENTO,ID_SUCURSAL,ID_REPARTIDOR,"
                + "FECHA_HORA_PEDIDO,ESTADO_PEDIDO,ACTIVO_PEDIDO) VALUES (1,1,1,1,1,'2025-05-01 10:00','pendiente',1);");
        db.execSQL("INSERT OR REPLACE INTO PEDIDO("
                + "ID_PEDIDO,ID_CLIENTE,ID_TIPO_EVENTO,ID_SUCURSAL,ID_REPARTIDOR,"
                + "FECHA_HORA_PEDIDO,ESTADO_PEDIDO,ACTIVO_PEDIDO) VALUES (2,2,2,2,2,'2025-05-01 11:00','enviado',1);");
        db.execSQL("INSERT OR REPLACE INTO PEDIDO("
                + "ID_PEDIDO,ID_CLIENTE,ID_TIPO_EVENTO,ID_SUCURSAL,ID_REPARTIDOR,"
                + "FECHA_HORA_PEDIDO,ESTADO_PEDIDO,ACTIVO_PEDIDO) VALUES (3,3,3,3,3,'2025-05-01 12:00','entregado',1);");
        db.execSQL("INSERT OR REPLACE INTO PEDIDO("
                + "ID_PEDIDO,ID_CLIENTE,ID_TIPO_EVENTO,ID_SUCURSAL,ID_REPARTIDOR,"
                + "FECHA_HORA_PEDIDO,ESTADO_PEDIDO,ACTIVO_PEDIDO) VALUES (4,4,4,4,4,'2025-05-01 13:00','cancelado',1);");
        db.execSQL("INSERT OR REPLACE INTO PEDIDO("
                + "ID_PEDIDO,ID_CLIENTE,ID_TIPO_EVENTO,ID_SUCURSAL,ID_REPARTIDOR,"
                + "FECHA_HORA_PEDIDO,ESTADO_PEDIDO,ACTIVO_PEDIDO) VALUES (5,5,5,5,5,'2025-05-01 14:00','pendiente',1);");

        // --- 12 – Datos para FACTURA ---
        db.execSQL("INSERT OR REPLACE INTO FACTURA("
                + "ID_FACTURA,ID_PEDIDO,FECHA_EMISION,MONTO_TOTAL,TIPO_PAGO,"
                + "ESTADO_FACTURA,ES_CREDITO) VALUES (1,1,'2025-05-01',50.00,'efectivo','Pagada',0);");
        db.execSQL("INSERT OR REPLACE INTO FACTURA("
                + "ID_FACTURA,ID_PEDIDO,FECHA_EMISION,MONTO_TOTAL,TIPO_PAGO,"
                + "ESTADO_FACTURA,ES_CREDITO) VALUES (2,2,'2025-05-01',60.00,'tarjeta','Pagada',0);");
        db.execSQL("INSERT OR REPLACE INTO FACTURA("
                + "ID_FACTURA,ID_PEDIDO,FECHA_EMISION,MONTO_TOTAL,TIPO_PAGO,"
                + "ESTADO_FACTURA,ES_CREDITO) VALUES (3,3,'2025-05-01',70.00,'bitcoin','Pagada',0);");
        db.execSQL("INSERT OR REPLACE INTO FACTURA("
                + "ID_FACTURA,ID_PEDIDO,FECHA_EMISION,MONTO_TOTAL,TIPO_PAGO,"
                + "ESTADO_FACTURA,ES_CREDITO) VALUES (4,4,'2025-05-01',40.00,'efectivo','Pendiente',0);");
        db.execSQL("INSERT OR REPLACE INTO FACTURA("
                + "ID_FACTURA,ID_PEDIDO,FECHA_EMISION,MONTO_TOTAL,TIPO_PAGO,"
                + "ESTADO_FACTURA,ES_CREDITO) VALUES (5,5,'2025-05-01',90.00,'tarjeta','Pagada',0);");

        // --- 13 – Datos para CREDITO ---
        db.execSQL("INSERT OR REPLACE INTO CREDITO("
                + "ID_CREDITO,ID_FACTURA,MONTO_AUTORIZADO_CREDITO,MONTO_PAGADO,"
                + "SALDO_PENDIENTE,FECHA_LIMITE_PAGO,ESTADO_CREDITO) "
                + "VALUES (1,1,50.00,25.00,25.00,'2025-06-01','Activo');");
        db.execSQL("INSERT OR REPLACE INTO CREDITO("
                + "ID_CREDITO,ID_FACTURA,MONTO_AUTORIZADO_CREDITO,MONTO_PAGADO,"
                + "SALDO_PENDIENTE,FECHA_LIMITE_PAGO,ESTADO_CREDITO) "
                + "VALUES (2,2,60.00,30.00,30.00,'2025-06-10','Activo');");
        db.execSQL("INSERT OR REPLACE INTO CREDITO("
                + "ID_CREDITO,ID_FACTURA,MONTO_AUTORIZADO_CREDITO,MONTO_PAGADO,"
                + "SALDO_PENDIENTE,FECHA_LIMITE_PAGO,ESTADO_CREDITO) "
                + "VALUES (3,3,70.00,35.00,35.00,'2025-06-15','Activo');");
        db.execSQL("INSERT OR REPLACE INTO CREDITO("
                + "ID_CREDITO,ID_FACTURA,MONTO_AUTORIZADO_CREDITO,MONTO_PAGADO,"
                + "SALDO_PENDIENTE,FECHA_LIMITE_PAGO,ESTADO_CREDITO) "
                + "VALUES (4,4,40.00,40.00,0.00,'2025-05-30','Pagado');");
        db.execSQL("INSERT OR REPLACE INTO CREDITO("
                + "ID_CREDITO,ID_FACTURA,MONTO_AUTORIZADO_CREDITO,MONTO_PAGADO,"
                + "SALDO_PENDIENTE,FECHA_LIMITE_PAGO,ESTADO_CREDITO) "
                + "VALUES (5,5,90.00,45.00,45.00,'2025-06-05','Activo');");

        // --- 14 - Datos para DATOSPRODUCTO ---
        db.execSQL("INSERT OR REPLACE INTO DATOSPRODUCTO("
                + "ID_SUCURSAL,ID_PRODUCTO,PRECIO_SUCURSAL_PRODUCTO,STOCK,"
                + "ACTIVO_DATOSPRODUCTO) VALUES (1,1,1.00,10,1);");
        db.execSQL("INSERT OR REPLACE INTO DATOSPRODUCTO("
                + "ID_SUCURSAL,ID_PRODUCTO,PRECIO_SUCURSAL_PRODUCTO,STOCK,"
                + "ACTIVO_DATOSPRODUCTO) VALUES (2,2,1.25,15,1);");
        db.execSQL("INSERT OR REPLACE INTO DATOSPRODUCTO("
                + "ID_SUCURSAL,ID_PRODUCTO,PRECIO_SUCURSAL_PRODUCTO,STOCK,"
                + "ACTIVO_DATOSPRODUCTO) VALUES (3,3,0.75,20,1);");
        db.execSQL("INSERT OR REPLACE INTO DATOSPRODUCTO("
                + "ID_SUCURSAL,ID_PRODUCTO,PRECIO_SUCURSAL_PRODUCTO,STOCK,"
                + "ACTIVO_DATOSPRODUCTO) VALUES (4,4,3.50,8,1);");
        db.execSQL("INSERT OR REPLACE INTO DATOSPRODUCTO("
                + "ID_SUCURSAL,ID_PRODUCTO,PRECIO_SUCURSAL_PRODUCTO,STOCK,"
                + "ACTIVO_DATOSPRODUCTO) VALUES (5,5,1.75,12,1);");

        // 15 – Datos para DIRECCION (incluyendo ACTIVO_DIRECCION)
        db.execSQL("INSERT OR REPLACE INTO DIRECCION("
                + "ID_CLIENTE,ID_DIRECCION,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,"
                + "DIRECCION_ESPECIFICA,DESCRIPCION_DIRECCION,ACTIVO_DIRECCION) "
                + "VALUES (1,1,1,1,1,'Col. Escalón #123','Casa esquina azul',1);");
        db.execSQL("INSERT OR REPLACE INTO DIRECCION("
                + "ID_CLIENTE,ID_DIRECCION,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,"
                + "DIRECCION_ESPECIFICA,DESCRIPCION_DIRECCION,ACTIVO_DIRECCION) "
                + "VALUES (2,2,2,2,2,'Santa Tecla Norte','Casa blanca dos niveles',1);");
        db.execSQL("INSERT OR REPLACE INTO DIRECCION("
                + "ID_CLIENTE,ID_DIRECCION,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,"
                + "DIRECCION_ESPECIFICA,DESCRIPCION_DIRECCION,ACTIVO_DIRECCION) "
                + "VALUES (3,3,3,3,3,'Col. Santa Lucía','Apartamento 2-B',1);");
        db.execSQL("INSERT OR REPLACE INTO DIRECCION("
                + "ID_CLIENTE,ID_DIRECCION,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,"
                + "DIRECCION_ESPECIFICA,DESCRIPCION_DIRECCION,ACTIVO_DIRECCION) "
                + "VALUES (4,4,4,4,4,'Ciudad Pacífica','Pasaje 4',1);");
        db.execSQL("INSERT OR REPLACE INTO DIRECCION("
                + "ID_CLIENTE,ID_DIRECCION,ID_DEPARTAMENTO,ID_MUNICIPIO,ID_DISTRITO,"
                + "DIRECCION_ESPECIFICA,DESCRIPCION_DIRECCION,ACTIVO_DIRECCION) "
                + "VALUES (5,5,5,5,5,'Usulután centro','Casa colonial',1);");

        db.execSQL("INSERT OR REPLACE INTO REPARTOPEDIDO(" +
                "ID_PEDIDO, ID_REPARTO_PEDIDO, HORA_ASIGNACION, UBICACION_ENTREGA, FECHA_HORA_ENTREGA) " +
                "VALUES (1, 1, '01/05/2025 10:30', 'Escalón', '01/05/2025 11:00');");

        db.execSQL("INSERT OR REPLACE INTO REPARTOPEDIDO(" +
                "ID_PEDIDO, ID_REPARTO_PEDIDO, HORA_ASIGNACION, UBICACION_ENTREGA, FECHA_HORA_ENTREGA) " +
                "VALUES (2, 1, '01/05/2025 11:30', 'Merliot', '01/05/2025 12:00');");

        db.execSQL("INSERT OR REPLACE INTO REPARTOPEDIDO(" +
                "ID_PEDIDO, ID_REPARTO_PEDIDO, HORA_ASIGNACION, UBICACION_ENTREGA, FECHA_HORA_ENTREGA) " +
                "VALUES (3, 1, '01/05/2025 12:30', 'Metapán', '01/05/2025 13:00');");

        db.execSQL("INSERT OR REPLACE INTO REPARTOPEDIDO(" +
                "ID_PEDIDO, ID_REPARTO_PEDIDO, HORA_ASIGNACION, UBICACION_ENTREGA, FECHA_HORA_ENTREGA) " +
                "VALUES (4, 1, '01/05/2025 13:30', 'San Miguel', '01/05/2025 14:00');");

        db.execSQL("INSERT OR REPLACE INTO REPARTOPEDIDO(" +
                "ID_PEDIDO, ID_REPARTO_PEDIDO, HORA_ASIGNACION, UBICACION_ENTREGA, FECHA_HORA_ENTREGA) " +
                "VALUES (5, 1, '01/05/2025 14:30', 'Usulután', '01/05/2025 15:00');");


        // 17 – Datos para DETALLEPEDIDO
        db.execSQL("INSERT OR REPLACE INTO DETALLEPEDIDO(" +
                "ID_PRODUCTO, ID_PEDIDO, CANTIDAD, SUBTOTAL) " +
                "VALUES (1, 1, 2, 2.00);");

        db.execSQL("INSERT OR REPLACE INTO DETALLEPEDIDO(" +
                "ID_PRODUCTO, ID_PEDIDO, CANTIDAD, SUBTOTAL) " +
                "VALUES (2, 2, 4, 5.00);");

        db.execSQL("INSERT OR REPLACE INTO DETALLEPEDIDO(" +
                "ID_PRODUCTO, ID_PEDIDO, CANTIDAD, SUBTOTAL) " +
                "VALUES (3, 3, 1, 0.75);");

        db.execSQL("INSERT OR REPLACE INTO DETALLEPEDIDO(" +
                "ID_PRODUCTO, ID_PEDIDO, CANTIDAD, SUBTOTAL) " +
                "VALUES (4, 4, 2, 7.00);");

        db.execSQL("INSERT OR REPLACE INTO DETALLEPEDIDO(" +
                "ID_PRODUCTO, ID_PEDIDO, CANTIDAD, SUBTOTAL) " +
                "VALUES (5, 5, 3, 5.25);");

    }
}
